name: Kotlin Build
 
on:
  push:
    branches: [ main ]
 
jobs:
  build:
    runs-on: ubuntu-latest
 
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: create wrapper
      run: chmod +x ./gradlew
      working-directory: Practicerun2.5
   
    - name: Build with Gradle
      run: ./gradlew build
      working-directory: Practice run2.5
